using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;

namespace ProjectEuler
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    public class Problem2 : BaseProblem
    {
        [Test]
        public void Problem2_Loop()
        {
            var n = new List<int> { 1, 2 };
            int x, y, z;
            do
            {
                x = n[n.Count - 2];
                y = n[n.Count - 1];
                z = x + y;
                n.Add(z);
            } while (z < 4000000);

            Assert.AreEqual(4613732, n.Where(m => m % 2 == 0).Sum());
        }
    }
}